
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action m1Action;
	private global::Gtk.Action m2Action;
	private global::Gtk.Action m3Action;
	private global::Gtk.Action m4Action;
	private global::Gtk.Action m5Action;
	private global::Gtk.Action m6Action;
	private global::Gtk.Action m7Action;
	private global::Gtk.Action m8Action;
	private global::Gtk.Action m9Action;
	private global::Gtk.Action m10Action;
	private global::Gtk.Action testAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Table _tabletext;
	private global::Gtk.Notebook _notebook;
	private global::Gtk.Label label2;
	private global::Gtk.Label label5;
	private global::Gtk.Label label6;
	private global::Gtk.Label label7;
	private global::Gtk.Table _tablebutton;
	private global::Gtk.Statusbar statusbar1;
	private global::Gtk.Label label1;
	private global::Gtk.ProgressBar progressbar1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.m1Action = new global::Gtk.Action ("m1Action", global::Mono.Unix.Catalog.GetString ("1"), null, null);
		this.m1Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("1");
		w1.Add (this.m1Action, null);
		this.m2Action = new global::Gtk.Action ("m2Action", global::Mono.Unix.Catalog.GetString ("2"), null, null);
		this.m2Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("2");
		w1.Add (this.m2Action, null);
		this.m3Action = new global::Gtk.Action ("m3Action", global::Mono.Unix.Catalog.GetString ("3"), null, null);
		this.m3Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("3");
		w1.Add (this.m3Action, null);
		this.m4Action = new global::Gtk.Action ("m4Action", global::Mono.Unix.Catalog.GetString ("4"), null, null);
		this.m4Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("4");
		w1.Add (this.m4Action, null);
		this.m5Action = new global::Gtk.Action ("m5Action", global::Mono.Unix.Catalog.GetString ("5"), null, null);
		this.m5Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("5");
		w1.Add (this.m5Action, null);
		this.m6Action = new global::Gtk.Action ("m6Action", global::Mono.Unix.Catalog.GetString ("6"), null, null);
		this.m6Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("6");
		w1.Add (this.m6Action, null);
		this.m7Action = new global::Gtk.Action ("m7Action", global::Mono.Unix.Catalog.GetString ("7"), null, null);
		this.m7Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("7");
		w1.Add (this.m7Action, null);
		this.m8Action = new global::Gtk.Action ("m8Action", global::Mono.Unix.Catalog.GetString ("8"), null, null);
		this.m8Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("8");
		w1.Add (this.m8Action, null);
		this.m9Action = new global::Gtk.Action ("m9Action", global::Mono.Unix.Catalog.GetString ("9"), null, null);
		this.m9Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("9");
		w1.Add (this.m9Action, null);
		this.m10Action = new global::Gtk.Action ("m10Action", global::Mono.Unix.Catalog.GetString ("10"), null, null);
		this.m10Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("10");
		w1.Add (this.m10Action, null);
		this.testAction = new global::Gtk.Action ("testAction", global::Mono.Unix.Catalog.GetString ("test"), null, null);
		this.testAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("test");
		w1.Add (this.testAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 5;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='m1Action' action='m1Action'/><menu name='m2Action' action='m2Action'/><menu name='m3Action' action='m3Action'/><menu name='m4Action' action='m4Action'/><menu name='m5Action' action='m5Action'/><menu name='m6Action' action='m6Action'/><menu name='m7Action' action='m7Action'/><menu name='m8Action' action='m8Action'/><menu name='m9Action' action='m9Action'/><menu name='m10Action' action='m10Action'><menuitem name='testAction' action='testAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 5;
		// Container child hbox1.Gtk.Box+BoxChild
		this._tabletext = new global::Gtk.Table (((uint)(11)), ((uint)(2)), false);
		this._tabletext.Name = "_tabletext";
		this._tabletext.RowSpacing = ((uint)(6));
		this._tabletext.ColumnSpacing = ((uint)(6));
		this.hbox1.Add (this._tabletext);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this._tabletext]));
		w3.Position = 0;
		w3.Expand = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this._notebook = new global::Gtk.Notebook ();
		this._notebook.CanFocus = true;
		this._notebook.Name = "_notebook";
		this._notebook.CurrentPage = 0;
		// Notebook tab
		global::Gtk.Label w4 = new global::Gtk.Label ();
		w4.Visible = true;
		this._notebook.Add (w4);
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("page1");
		this._notebook.SetTabLabel (w4, this.label2);
		this.label2.ShowAll ();
		// Notebook tab
		global::Gtk.Label w5 = new global::Gtk.Label ();
		w5.Visible = true;
		this._notebook.Add (w5);
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("page2");
		this._notebook.SetTabLabel (w5, this.label5);
		this.label5.ShowAll ();
		// Notebook tab
		global::Gtk.Label w6 = new global::Gtk.Label ();
		w6.Visible = true;
		this._notebook.Add (w6);
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("page3");
		this._notebook.SetTabLabel (w6, this.label6);
		this.label6.ShowAll ();
		// Notebook tab
		global::Gtk.Label w7 = new global::Gtk.Label ();
		w7.Visible = true;
		this._notebook.Add (w7);
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("page4");
		this._notebook.SetTabLabel (w7, this.label7);
		this.label7.ShowAll ();
		this.hbox1.Add (this._notebook);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this._notebook]));
		w8.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this._tablebutton = new global::Gtk.Table (((uint)(11)), ((uint)(2)), false);
		this._tablebutton.Name = "_tablebutton";
		this._tablebutton.RowSpacing = ((uint)(6));
		this._tablebutton.ColumnSpacing = ((uint)(6));
		this.hbox1.Add (this._tablebutton);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this._tablebutton]));
		w9.Position = 2;
		w9.Expand = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w10.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.statusbar1.Add (this.label1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.label1]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.progressbar1 = new global::Gtk.ProgressBar ();
		this.progressbar1.Name = "progressbar1";
		this.statusbar1.Add (this.progressbar1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.progressbar1]));
		w12.Position = 2;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 556;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
